# Generated by Django 2.2 on 2019-05-05 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_ID', models.AutoField(primary_key=True, serialize=False)),
                ('sex', models.CharField(choices=[('M', 'man'), ('W', 'woman')], default='M', max_length=1)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('institute', models.CharField(blank=True, max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('citation_times', models.IntegerField(blank=True, default=0)),
                ('article_numbers', models.IntegerField(blank=True, default=0)),
                ('h_index', models.IntegerField(blank=True, default=0)),
                ('g_index', models.IntegerField(blank=True, default=0)),
                ('avator', models.ImageField(blank=True, upload_to='demo1/static/author_avator')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('authors', models.TextField(blank=True)),
                ('intro', models.TextField(blank=True)),
                ('url', models.TextField(blank=True)),
                ('price', models.IntegerField(default=0)),
                ('Type', models.CharField(choices=[('P1', 'Paper'), ('P2', 'Patent'), ('P3', 'Project')], max_length=2)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('publish_date', models.CharField(blank=True, max_length=255)),
                ('citation_numbers', models.IntegerField(blank=True, default=0)),
                ('agency', models.CharField(blank=True, max_length=255)),
                ('patent_number', models.TextField(blank=True)),
                ('patent_applicant_number', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='demo1/static/files')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('passwd', models.CharField(max_length=255)),
                ('mail', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(default='', max_length=255)),
                ('Type', models.CharField(choices=[('U', 'User'), ('E', 'Expert'), ('A', 'Admin')], max_length=1)),
                ('introduction', models.TextField(blank=True)),
                ('institute', models.CharField(blank=True, max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.CharField(blank=True, max_length=255)),
                ('balance', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('avator', models.ImageField(blank=True, upload_to='demo1/static/user_avator')),
            ],
        ),
        migrations.CreateModel(
            name='U2E_apply_form',
            fields=[
                ('created_time', models.DateTimeField(auto_created=True)),
                ('form_ID', models.AutoField(primary_key=True, serialize=False)),
                ('approve_time', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('name', models.CharField(default=' ', max_length=255)),
                ('institute', models.CharField(blank=True, max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostweb.User')),
            ],
        ),
        migrations.CreateModel(
            name='publish_item_application_form',
            fields=[
                ('created_time', models.DateTimeField(auto_created=True)),
                ('f_ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.TextField(blank=True)),
                ('intro', models.TextField(blank=True)),
                ('url', models.TextField(blank=True)),
                ('price', models.IntegerField(default=0)),
                ('Type', models.CharField(choices=[('P1', 'Paper'), ('P2', 'Patent'), ('P3', 'Project')], max_length=2)),
                ('passed', models.BooleanField(default=False)),
                ('author_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostweb.Author')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='bind',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='hostweb.User'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_time', models.DateTimeField(auto_created=True)),
                ('t_ID', models.AutoField(primary_key=True, serialize=False)),
                ('resource_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostweb.Resource')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostweb.User')),
            ],
            options={
                'unique_together': {('user_ID', 'resource_ID')},
            },
        ),
        migrations.CreateModel(
            name='starForm',
            fields=[
                ('created_time', models.DateTimeField(auto_created=True)),
                ('form_ID', models.AutoField(primary_key=True, serialize=False)),
                ('resource_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostweb.Resource')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostweb.User')),
            ],
            options={
                'unique_together': {('user_ID', 'resource_ID')},
            },
        ),
        migrations.CreateModel(
            name='ItemCart',
            fields=[
                ('r_ID', models.AutoField(primary_key=True, serialize=False)),
                ('resource_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostweb.Resource')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostweb.User')),
            ],
            options={
                'unique_together': {('user_ID', 'resource_ID')},
            },
        ),
        migrations.CreateModel(
            name='A2R',
            fields=[
                ('form_ID', models.AutoField(primary_key=True, serialize=False)),
                ('author_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostweb.Author')),
                ('resource_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostweb.Resource')),
            ],
            options={
                'unique_together': {('author_ID', 'resource_ID')},
            },
        ),
        migrations.CreateModel(
            name='A2A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s', to='hostweb.Author')),
                ('author2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t', to='hostweb.Author')),
            ],
            options={
                'unique_together': {('author1', 'author2')},
            },
        ),
    ]
