# Generated by Django 2.2 on 2019-04-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='Type',
            field=models.CharField(choices=[('U', 'User'), ('E', 'Expert'), ('A', 'Admin')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
