# Generated by Django 2.2 on 2019-04-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostweb', '0003_author_avator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
