# Generated by Django 2.2 on 2019-04-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostweb', '0003_auto_20190415_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='institute',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(default='', max_length=255),
        ),
    ]
