# Generated by Django 2.2 on 2019-04-30 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostweb', '0004_auto_20190430_1207'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='a2r',
            unique_together={('author_ID', 'resource_ID')},
        ),
        migrations.AlterUniqueTogether(
            name='itemcart',
            unique_together={('user_ID', 'resource_ID')},
        ),
    ]
