# Generated by Django 2.2 on 2019-04-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostweb', '0005_auto_20190415_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(blank=True),
        ),
    ]
