# Generated by Django 2.2 on 2019-04-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostweb', '0006_auto_20190415_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
