# Generated by Django 2.2 on 2019-04-30 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostweb', '0006_user_avator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('user_ID', 'resource_ID')},
        ),
        migrations.CreateModel(
            name='A2A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s', to='hostweb.Author')),
                ('author2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t', to='hostweb.Author')),
            ],
            options={
                'unique_together': {('author1', 'author2')},
            },
        ),
    ]
