# Generated by Django 2.2 on 2019-04-15 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostweb', '0007_auto_20190415_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.TextField(blank=True)),
                ('intro', models.TextField(blank=True)),
                ('url', models.TextField(blank=True)),
                ('price', models.IntegerField(default=0)),
                ('Type', models.CharField(choices=[('P1', 'Paper'), ('P2', 'Patent'), ('P3', 'Project')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_ID', models.AutoField(primary_key=True, serialize=False)),
                ('sex', models.CharField(choices=[('M', 'man'), ('W', 'woman')], max_length=1)),
                ('name', models.CharField(max_length=255)),
                ('institute', models.CharField(blank=True, max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('bind', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='hostweb.User')),
            ],
        ),
    ]
