# Generated by Django 2.2 on 2019-04-15 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostweb', '0008_auto_20190415_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='U2E_apply_form',
            fields=[
                ('form_ID', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField()),
                ('approve_time', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostweb.User')),
            ],
        ),
    ]
