# Generated by Django 2.2 on 2019-04-15 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostweb', '0010_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='starForm',
            fields=[
                ('form_ID', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField()),
                ('resource_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostweb.Resource')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostweb.User')),
            ],
        ),
    ]
