# Generated by Django 2.2 on 2019-04-16 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostweb', '0011_starform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starform',
            name='created_time',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='u2e_apply_form',
            name='created_time',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_time', models.DateTimeField(auto_created=True)),
                ('t_ID', models.AutoField(primary_key=True, serialize=False)),
                ('resource_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostweb.Resource')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostweb.User')),
            ],
        ),
    ]
