# Generated by Django 2.2 on 2019-04-16 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostweb', '0012_auto_20190416_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='article_numbers',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='citation_times',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='g_index',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='h_index',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='author',
            name='bind',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='hostweb.User', unique=True),
        ),
        migrations.CreateModel(
            name='A2R',
            fields=[
                ('form_ID', models.AutoField(primary_key=True, serialize=False)),
                ('author_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostweb.Author')),
                ('resource_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostweb.Resource')),
            ],
        ),
    ]
