# Generated by Django 2.2 on 2019-04-16 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostweb', '0014_auto_20190416_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='u2e_apply_form',
            name='domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='u2e_apply_form',
            name='institute',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='u2e_apply_form',
            name='name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.CreateModel(
            name='ItemCart',
            fields=[
                ('r_ID', models.AutoField(primary_key=True, serialize=False)),
                ('resource_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostweb.Resource')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostweb.User')),
            ],
        ),
    ]
