# Generated by Django 2.2 on 2019-04-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostweb', '0016_publish_item_application_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='sex',
            field=models.CharField(choices=[('M', 'man'), ('W', 'woman')], default='M', max_length=1),
        ),
    ]
