# Generated by Django 2.2 on 2019-04-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostweb', '0017_auto_20190428_1203'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='starform',
            unique_together={('user_ID', 'resource_ID')},
        ),
    ]
