# Generated by Django 2.2 on 2019-04-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostweb', '0019_auto_20190428_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='agency',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resource',
            name='citation_numbers',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='patent_applicant_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='patent_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='published_data',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resource',
            name='publisher',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
